name: CI/CD for Portfolio Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          CI: false # This prevents treating warnings as errors

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' # Only deploy on master branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }}
          publish_dir: ./build
          cname: ${{ secrets.CNAME }} # Optional: If you have a custom domain
          enable_jekyll: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy to GitHub Pages"
